CREATE TABLE APP_USER
(
    ID       BIGINT       NOT NULL,
    USERNAME VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(255),
    SALT     VARCHAR(64),
    ENABLED  BOOLEAN      NOT NULL,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

ALTER TABLE APP_USER ADD CONSTRAINT PK_APP_USERPRIMARY PRIMARY KEY (ID);

CREATE TABLE USERS_ROLES
(
    ROLE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CONSTRAINT PK_USERS_ROLES PRIMARY KEY (ROLE_ID, USER_ID)
);

ALTER TABLE APP_USER ADD CONSTRAINT UC_APP_USER_USERNAME UNIQUE (USERNAME);

ALTER TABLE USERS_ROLES ADD CONSTRAINT FK_USEROL_ON_ROLE FOREIGN KEY (ROLE_ID) REFERENCES APP_ROLE (ID);

ALTER TABLE USERS_ROLES ADD CONSTRAINT FK_USEROL_ON_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER (ID);