CREATE TABLE APP_CUSTOMER
(
    ID         BIGINT NOT NULL,
    NAME       VARCHAR(255),
    SUR_NAME   VARCHAR(255),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

ALTER TABLE APP_CUSTOMER
    ADD CONSTRAINT PK_APP_CUSTOMER PRIMARY KEY (ID);