CREATE TABLE APP_ACCOUNT
(
    ACCOUNT_ID       BIGINT NOT NULL,
    TYPE             INT,
    ACCOUNT_NUMBER   VARCHAR(255),
    INITIAL_CREDIT   DECIMAL,
    AVAILABLE_CREDIT DECIMAL,
    CREATED_AT       TIMESTAMP,
    UPDATED_AT       TIMESTAMP,
    CUSTOMER_ID       BIGINT NOT NULL
);

ALTER TABLE APP_ACCOUNT
    ADD CONSTRAINT PK_APP_ACCOUNT PRIMARY KEY (ACCOUNT_ID);

ALTER TABLE app_account
    ADD CONSTRAINT FK_APP_ACCOUNT_ON_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES APP_CUSTOMER (ID);